tenant_prefix|bread
tenant_name|Bread Pay
domain_sandbox|https://api-preview.platform.breadpayments.com/api
domain_production|https://api.platform.breadpayments.com/api
sdk_sandbox|https://connect-preview.breadpayments.com/sdk.js
sdk_production|https://connect.breadpayments.com/sdk.js
currency|USD
cpb_url_sandbox|https://api.sp-pv-ads.ue2.breadgateway.net/api/core-plugin-backend
cpb_url_production|https://api.pp-prod-ads.ue2.breadgateway.net/api/core-plugin-backend
