tenant_name: Bread Pay
gateway_id: bread_finance
tenant_prefix: bread
sdk_sandbox: https://connect-preview.breadpayments.com/sdk.js
sdk_production: https://connect.breadpayments.com/sdk.js
platform_domain_sandbox_api: https://api-preview.platform.breadpayments.com/api
platform_domain_production_api: https://api.platform.breadpayments.com/api
currency: USD
cpb_url_sandbox: https://api.sp-pv-ads.ue2.breadgateway.net/api/core-plugin-backend
cpb_url_production: https://api.pp-prod-ads.ue2.breadgateway.net/api/core-plugin-backend
